### ISSUE TITLE
why do u use RockDB

### ISSUE THREAD

**Issue by HelloTo4x** [burtcorp/rocksdb-jruby#1]
Hi, why do you choose RockDB instead of other DB like MongoDB, MySQL......thank u so much

**Comment by stenlarsson** [comment]
We are currently not using RocksDB, so I'm not in a good position to answer your question. This repository only contains JRuby bindings for RocksDB, not RocksDB itself, so I think you will find a better answer over on the official homepage: http://rocksdb.org/.
